// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 13/8/2026, 10:16:50 am
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["F:/My Projects/Afsad/components/**/*.{vue,js,jsx,mjs,ts,tsx}","F:/My Projects/Afsad/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","F:/My Projects/Afsad/components/**/*.{vue,js,jsx,mjs,ts,tsx}","F:/My Projects/Afsad/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","F:/My Projects/Afsad/plugins/**/*.{js,ts,mjs}","F:/My Projects/Afsad/composables/**/*.{js,ts,mjs}","F:/My Projects/Afsad/utils/**/*.{js,ts,mjs}","F:/My Projects/Afsad/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","F:/My Projects/Afsad/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","F:/My Projects/Afsad/app.config.{js,ts,mjs}","F:/My Projects/Afsad/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;